version: "3.8"

name: paracor

services:
  backend:
    build: ./backend
    container_name: paracor-backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - paracor-net

  frontend:
    build: ./frontend
    container_name: paracor-frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./frontend/.env.local
    restart: unless-stopped
    networks:
      - paracor-net

  db:
    image: postgres:15
    container_name: paracor-db
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - paracor-net

  nginx:
    image: nginx:alpine
    container_name: paracor-nginx
    ports:
      - "82:80"
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - paracor-net

volumes:
  postgres_data:

networks:
  paracor-net:
    driver: bridge
